import os
import subprocess
import sys
from pathlib import Path

from sidecar import steam
from sidecar.context import InstallContext, LaunchContext
from sidecar.hook import Hook, load_hook
from sidecar.manifest import Manifest
from sidecar.registry import find_hook_script

_LAUNCHER_TEMPLATE = """\
#!/usr/bin/env bash
# Generated by proton-sidecar — do not edit manually
# App: {app_name}  Game AppID: {game_appid}
set -euo pipefail

export STEAM_COMPAT_DATA_PATH="{compat_data_path}"
export STEAM_COMPAT_CLIENT_INSTALL_PATH="{steam_dir}"
{extra_env}
exec "{proton_bin}" run "{wine_exe_path}" {args}
"""


def write_launcher(manifest: Manifest, ctx: InstallContext) -> None:
    """Generate launch.sh in ctx.install_dir for use as a standalone launcher."""
    exe_linux = ctx.app_dir / manifest.launch.exe
    wine_path = steam.linux_to_wine_path(exe_linux)
    compat_data = ctx.prefix_dir.parent.parent

    extra_env = "\n".join(
        f'export {k}="{v}"' for k, v in manifest.launch.env.items()
    )
    args_str = " ".join(f'"{a}"' for a in manifest.launch.args)

    content = _LAUNCHER_TEMPLATE.format(
        app_name=manifest.app.name,
        game_appid=ctx.game_appid,
        compat_data_path=str(compat_data),
        steam_dir=str(ctx.steam_dir),
        extra_env=extra_env,
        proton_bin=str(ctx.proton_bin),
        wine_exe_path=wine_path,
        args=args_str,
    )

    launcher = ctx.install_dir / "launch.sh"
    launcher.write_text(content)
    launcher.chmod(0o755)


def run_app(manifest: Manifest, ctx: InstallContext, extra_args: list[str]) -> None:
    """Run the app via Proton with hook lifecycle (pre_launch → run → post_launch)."""
    exe_path = ctx.app_dir / manifest.launch.exe
    lctx = LaunchContext(
        steam_dir=ctx.steam_dir,
        game_appid=ctx.game_appid,
        game_dir=ctx.game_dir,
        prefix_dir=ctx.prefix_dir,
        install_dir=ctx.install_dir,
        app_dir=ctx.app_dir,
        proton_bin=ctx.proton_bin,
        exe_path=exe_path,
        args=list(manifest.launch.args) + extra_args,
    )

    hook: Hook | None = None
    if manifest.install.script:
        hook_path = find_hook_script(manifest.app.id, manifest.install.script)
        hook = load_hook(hook_path, manifest)
        hook.pre_launch(lctx)

    env = {
        **os.environ,
        "STEAM_COMPAT_DATA_PATH": str(ctx.prefix_dir.parent.parent),
        "STEAM_COMPAT_CLIENT_INSTALL_PATH": str(ctx.steam_dir),
        **manifest.launch.env,
    }

    cmd = [
        str(ctx.proton_bin),
        "run",
        steam.linux_to_wine_path(exe_path),
        *manifest.launch.args,
        *extra_args,
    ]
    result = subprocess.run(cmd, env=env)

    if hook:
        hook.post_launch(lctx)

    sys.exit(result.returncode)
