#!/usr/bin/env python3
"""Compile apps/*/manifest.toml into apps/_index.toml."""
import sys
import tomllib
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
APPS_DIR = REPO_ROOT / "apps"

sys.path.insert(0, str(REPO_ROOT))

from sidecar.manifest import Manifest, ManifestError


def build_index() -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# Auto-generated by scripts/build_index.py — do not edit manually",
        f"# Generated: {now}",
        "",
    ]

    manifests = sorted(APPS_DIR.glob("*/manifest.toml"))
    if not manifests:
        lines.append("apps = []")
        return "\n".join(lines) + "\n"

    for mf in manifests:
        try:
            m = Manifest.from_toml(mf)
        except ManifestError as exc:
            print(f"Warning: skipping {mf}: {exc}", file=sys.stderr)
            continue

        tags_toml = "[" + ", ".join(f'"{t}"' for t in m.meta.tags) + "]"
        games_toml = "[" + ", ".join(str(g) for g in m.requires.games) + "]"

        lines += [
            "[[apps]]",
            f'id          = "{m.app.id}"',
            f'name        = "{m.app.name}"',
            f'description = "{m.app.description}"',
            f'homepage    = "{m.app.homepage}"',
            f"tags        = {tags_toml}",
            f"games       = {games_toml}",
            "",
        ]

    return "\n".join(lines)


if __name__ == "__main__":
    output = build_index()
    index_path = APPS_DIR / "_index.toml"
    index_path.write_text(output)
    print(f"Written {index_path}")
